"""caching

Revision ID: 0045d62f9d45
Revises: 
Create Date: 2023-05-06 21:10:14.208152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0045d62f9d45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('last_cache_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artist_last_cache_date'), ['last_cache_date'], unique=False)

    op.create_table('lyric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('lyric', sa.String(), nullable=True),
    sa.Column('track_lyric_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('last_cache_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('owner_id', sa.String(length=120), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_last_cache_date'), ['last_cache_date'], unique=False)

    op.create_table('track',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('last_cache_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('preview_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_last_cache_date'), ['last_cache_date'], unique=False)

    op.create_table('track_artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastCacheDate', sa.DateTime(), nullable=True),
    sa.Column('artist_id', sa.String(length=120), nullable=True),
    sa.Column('track_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track_artist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_artist_lastCacheDate'), ['lastCacheDate'], unique=False)

    op.create_table('track_lyrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_cache_date', sa.DateTime(), nullable=True),
    sa.Column('lyric_count', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track_lyrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_lyrics_last_cache_date'), ['last_cache_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_lyrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_lyrics_last_cache_date'))

    op.drop_table('track_lyrics')
    with op.batch_alter_table('track_artist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_artist_lastCacheDate'))

    op.drop_table('track_artist')
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_last_cache_date'))

    op.drop_table('track')
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_last_cache_date'))

    op.drop_table('playlist')
    op.drop_table('lyric')
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_last_cache_date'))

    op.drop_table('artist')
    # ### end Alembic commands ###
