"""track release caching

Revision ID: 07b7db1ee746
Revises: ff224e3553dc
Create Date: 2023-05-16 22:02:16.749029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b7db1ee746'
down_revision = 'ff224e3553dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.DateTime(), nullable=True))
        batch_op.execute("DELETE FROM track") # clear cache as format changed - Alex
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
