"""artist caching

Revision ID: d41bc94d1cd1
Revises: 07b7db1ee746
Create Date: 2023-05-17 12:32:44.124271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41bc94d1cd1'
down_revision = '07b7db1ee746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracks_last_cache_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_artist_tracks_last_cache_date'), ['tracks_last_cache_date'], unique=False)
        batch_op.execute("DELETE FROM artist") # clear cache as format changed - Alex

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_tracks_last_cache_date'))
        batch_op.drop_column('tracks_last_cache_date')

    # ### end Alembic commands ###
